# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  name: minio-client
spec:
  replicas: 1
  selector:
    # labels the pods
    matchLabels:
      app: crm
  template:
    metadata:
      labels:
        # The label the pods created from the pod template should have
        app: crm
        name: minio-client
    spec:
      containers:
        # The container name to execute pods
        - name: minio-client
          image: "docker.relationc.com/minio-client:latest"
          envFrom:
            - configMapRef:
                name: "crm-env"
          ports:
            - containerPort: 3000 # Node port
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: minio-client
spec:
  selector:
    app: crm
    name: minio-client
  ports:
    - port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-client
  annotations:
    cert-manager.io/issuer: "crm-issuer"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - hosts:
        - api.relationc.com
      secretName: api-ssl
  rules:
    - host: api.relationc.com
      http:
        paths:
          - path: /upload
            pathType: Prefix
            backend:
              service:
                name: minio-client
                port:
                  number: 3000

